###
GET http://localhost:8080

###
POST http://localhost:8080/recipes/
Content-Type: application/json

{
  "name": "Ham and cheese toasties",
  "description": "sdligha;sdojaldfiSD;AS"
}

###
GET http://localhost:8080/recipes

###
GET http://localhost:8080/recipes/1

###
PUT http://localhost:8080/recipes/1
Content-Type: application/json

{
  "name": "Ham and cheese toasties",
  "description": "SLDFIGHSLDNLASD"
}

###
GET http://localhost:8080/recipes/1

###
DELETE http://localhost:8080/recipes/1

###
GET http://localhost:8080/recipes/2